<a href="https://colab.research.google.com/github/dev-achintha/Sri_Lanka-Tourism_Forcasting_Model/blob/SARIMA/notebooks/Sri_Lankan_TourismForecastModel_Prophet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt

In [2]:
class TourismForecastingModel:
    def __init__(self):
        self.country_data = None
        self.total_data = None
        self.model = None
        self.scenarios = {}

    def load_data(self, country_file, total_file):
        self._load_country_wise_data(country_file)
        self._load_monthly_total_data(total_file)

    def _load_country_wise_data(self, file_path):
        df = pd.read_csv(file_path)
        df_melted = df.melt(id_vars=['YEAR', 'COUNTRY'],
                            var_name='MONTH',
                            value_name='ARRIVALS')
        df_melted = df_melted[df_melted['MONTH'] != 'TOTAL UP TO END OF DECEMBER']
        df_melted['DATE'] = pd.to_datetime(df_melted['YEAR'].astype(str) + '-' + df_melted['MONTH'], format='%Y-%B')
        df_melted['ARRIVALS'] = df_melted['ARRIVALS'].replace('PENDING', np.nan).astype(float)
        self.country_data = df_melted.pivot(index='DATE', columns='COUNTRY', values='ARRIVALS')
        self.country_data = self.country_data.sort_index()

    def _load_monthly_total_data(self, file_path):
        df = pd.read_csv(file_path)
        df['DATE'] = pd.to_datetime(df['YEAR'].astype(str) + '-' + df['MONTH'], format='%Y-%B')
        df['ARRIVALS'] = df['ARRIVALS'].replace('PENDING', np.nan).astype(float)
        self.total_data = df.set_index('DATE')['ARRIVALS']
        self.total_data = self.total_data.sort_index()

    def add_scenario(self, name, start_date, impact_level):
        self.scenarios[name] = {'start_date': pd.to_datetime(start_date), 'impact_level': impact_level}

    def prepare_exog_variables(self, future_dates):
        all_dates = self.total_data.index.union(self.country_data.index).union(future_dates)
        exog = pd.DataFrame(index=all_dates, columns=self.scenarios.keys())
        for name, scenario in self.scenarios.items():
            exog.loc[scenario['start_date']:, name] = scenario['impact_level']
        exog = exog.fillna(0)
        return exog

    def train_model(self, country=None, exog=None):
        if country:
            train_data = self.country_data[country].dropna()
        else:
            total_from_countries = self.country_data.sum(axis=1)
            combined_data = pd.concat([total_from_countries, self.total_data], axis=1)
            combined_data.columns = ['Country Sum', 'Total']
            train_data = combined_data.dropna()

        self.model = SARIMAX(train_data, exog=exog.loc[train_data.index], order=(1, 1, 1), seasonal_order=(1, 1, 1, 12))
        self.model = self.model.fit()

    def make_predictions(self, steps, exog, country=None):
        forecast = self.model.get_forecast(steps=steps, exog=exog.loc[self.total_data.index[-1]+pd.DateOffset(months=1):])
        return forecast.predicted_mean

    def plot_results(self, predictions, country=None):
        plt.figure(figsize=(12, 6))
        if country:
            plt.plot(self.country_data.index, self.country_data[country], label='Historical Data')
            title = f'Tourism Arrivals Forecast for {country}'
        else:
            plt.plot(self.total_data.index, self.total_data, label='Historical Total')
            plt.plot(self.country_data.index, self.country_data.sum(axis=1), label='Sum of Countries')
            title = 'Total Tourism Arrivals Forecast'
        plt.plot(predictions.index, predictions, label='Forecast')
        plt.legend()
        plt.title(title)
        plt.xlabel('Date')
        plt.ylabel('Number of Arrivals')
        plt.show()

    def update_model(self, new_country_data=None, new_total_data=None):
        if new_country_data is not None:
            new_country_data = new_country_data.replace('PENDING', np.nan).astype(float)
            self.country_data = pd.concat([self.country_data, new_country_data])
        if new_total_data is not None:
            new_total_data = new_total_data.replace('PENDING', np.nan).astype(float)
            self.total_data = pd.concat([self.total_data, new_total_data])

In [8]:
df1=pd.read_csv('https://raw.githubusercontent.com/dev-achintha/Sri_Lanka-Tourism_Forcasting_Model/SARIMA/dataset/2014-2024-monthly-tourist-arrivals-sl-csv.csv')
df2=pd.read_csv('https://raw.githubusercontent.com/dev-achintha/Sri_Lanka-Tourism_Forcasting_Model/SARIMA/dataset/2018-2024-Country-based-monthly-tourist-arrivals-sl-csv.csv')

df1.head()

   Year     Month Arrivals
0  2014   January   146575
1  2014  February   141878
2  2014     March   133048
3  2014     April   112631
4  2014       May    90046

In [9]:
df2.head()

,YEAR,COUNTRY,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER,TOTAL UP TO END OF DECEMBER
0,2018,AFGHANISTAN,83.0,150.0,112.0,40.0,108.0,44.0,47.0,78.0,34.0,41,52,72,861.0
1,2019,AFGHANISTAN,49.0,47.0,59.0,38.0,2.0,12.0,47.0,54.0,50.0,22,55,38,473.0
2,2020,AFGHANISTAN,65.0,64.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,146.0
3,2021,AFGHANISTAN,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,4.0,0,1,5,15.0
4,2022,AFGHANISTAN,0.0,2.0,16.0,0.0,1.0,0.0,2.0,0.0,0.0,0,7,11,39.0

In [10]:
# Usage example
model = TourismForecastingModel()
model.load_data('https://raw.githubusercontent.com/dev-achintha/Sri_Lanka-Tourism_Forcasting_Model/SARIMA/dataset/2014-2024-monthly-tourist-arrivals-sl-csv.csv', 'https://raw.githubusercontent.com/dev-achintha/Sri_Lanka-Tourism_Forcasting_Model/SARIMA/dataset/2018-2024-Country-based-monthly-tourist-arrivals-sl-csv.csv')

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['YEAR', 'COUNTRY']"

In [ ]:

# Prepare exogenous variables
future_dates = pd.date_range(start=max(model.total_data.index[-1], model.country_data.index[-1]), periods=24, freq='M')
exog = model.prepare_exog_variables(future_dates)

In [ ]:

# For country-specific forecast
model.train_model(country='AFGHANISTAN', exog=exog)
predictions = model.make_predictions(steps=24, exog=exog, country='AFGHANISTAN')
model.plot_results(predictions, country='AFGHANISTAN')

In [ ]:

# For total forecast
model.train_model(exog=exog)
predictions = model.make_predictions(steps=24, exog=exog)
model.plot_results(predictions)

In [ ]:

# Update model with new data (example)
new_country_data = pd.DataFrame({'AFGHANISTAN': [150, 180]},
                                index=pd.date_range(start=model.country_data.index[-1]+pd.DateOffset(months=1), periods=2, freq='M'))
new_total_data = pd.DataFrame({'ARRIVALS': [150000, 180000]},
                              index=pd.date_range(start=model.total_data.index[-1]+pd.DateOffset(months=1), periods=2, freq='M'))
model.update_model(new_country_data=new_country_data, new_total_data=new_total_data)

In [ ]:
# prompt: save this notebook as an html

!jupyter nbconvert --to html /content/Tourism_Forecasting.ipynb